### ISSUE TITLE
Not nearly all songs showing up in plugin

### ISSUE THREAD

**Issue by rbclark** [nvbn/rhythmbox-gmusic#14]
First off I would like to say this is quite possibly the best use I have found for google music so far.

That being said, I have just imported by google music library into rhythmbox using this plugin and am only seeing 76 of my 10,000 songs, and I am unable to get it to pull any more, I have installed the latest from the git repo, is there any additional step I should take to pull in all of the songs?

**Comment by nvbn** [comment]
Can you run rhythmbox in terminal and post output here?

**Comment by rbclark** [comment]
Sure, this is what I'm getting for this plugin error wise:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rhythmboxgmusic/**init**.py", line 180, in init_songs
    int(song['track']),
KeyError: 'track'

**Comment by nvbn** [comment]
Try to update and repeat again.

**Comment by rbclark** [comment]
Just tried it out and am now able to pull down all of my songs, it seems the fix has worked, thank you!
