### ISSUE TITLE
Add 14.04 PPA

### ISSUE THREAD

**Issue by nilsmedina** [nvbn/rhythmbox-gmusic#45]
Would it be possible to add ppa for Ubuntu 14.04?
cheers!

**Comment by p0lar-bear** [comment]
I can't speak for @nvbn, but I don't think it will happen any time soon. This plugin only works with rhythmbox 2.99 and earlier, and Ubuntu's repos only have 3.x for Trusty. See #44.

**Comment by nilsmedina** [comment]
ok, good to know! thanks.

So I guess the only way to have it in 14.04 is to downgrade Rhythmbox, right?

**Comment by p0lar-bear** [comment]
Yep! I got it 2.99 installed on my 14.04 machine, just had to add Saucy's repo to my sources.

**Comment by nilsmedina** [comment]
cheers!

**Comment by BigTA78** [comment]
So, I've downgraded to Rhythmbox 2.99, added the nvbn-rm PPA and sudo apt-get updated, but I don't see the rythmbox-gmusic plugin. What am I doing wrong?
I just see these
rhythmbox-ampache            rhythmbox-plugin-magnatune
rhythmbox-data               rhythmbox-plugins
rhythmbox-dbg                rhythmbox-plugin-visualizer
rhythmbox-dev                rhythmbox-plugin-zeitgeist
rhythmbox-doc                rhythmbox-radio-browser
rhythmbox-mozilla            rhythmbox-ubuntuone
rhythmbox-plugin-cdrecorder
